# Generated by Django 5.2.11 on 2026-02-21 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('domain_interest', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('LAW', 'Law'), ('BIO', 'Biomedical'), ('ENG', 'Engineering'), ('ECE', 'Electronics and Communication'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('skills', models.CharField(help_text='Comma-separated skills', max_length=255)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('incoscore', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('HACKATHON', 'Hackathon'), ('INTERNSHIP', 'Internship'), ('RESEARCH', 'Research Paper'), ('COMPETITION', 'Competition Result')], max_length=20)),
                ('description', models.TextField()),
                ('date_achieved', models.DateField()),
                ('link', models.URLField(blank=True)),
                ('score_value', models.IntegerField(default=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.studentprofile')),
            ],
        ),
    ]
