# Generated by Django 5.2.11 on 2026-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='coding_performance',
            field=models.IntegerField(default=0, help_text='Score from 0-100 based on platform tasks'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='score_value',
            field=models.IntegerField(default=50),
        ),
    ]
