# Generated by Django 5.2.11 on 2026-02-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='eligibility_criteria',
            field=models.TextField(blank=True),
        ),
    ]
