# Generated by Django 5.2.11 on 2026-02-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_university_alter_opportunity_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='eligibility_criteria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
