# Generated by Django 5.2.11 on 2026-02-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_alter_opportunity_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='event_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
